source 'https://rubygems.org'

gem 'eventmachine'
gem 'falcon'
gem 'gh-archive'
gem 'mongoid', '~> 7.0'
gem 'puma'
gem 'rack'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'
gem 'thin'
gem 'webrick'
gem 'rufus-scheduler'
gem "bundler-audit"
